import type { NextPage } from 'next'
import Head from 'next/head'
import { FooterComponent } from '../component/FooterComponent'
import { NavBarComponent } from '../component/NavBarComponent'
import { TestimonialComponent } from '../component/TestimonialComponent'
import testData from './../testData/index.json';



const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <br/>
      <NavBarComponent />
      <TestimonialComponent  testimonials={testData}/> 
      <FooterComponent />
    </div>
  )
}

export default Home
